name: "Test Report"

on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - uses: dorny/test-reporter@df6247429542221bc30d46a036ee47af1102c451 # v2
        with:
          artifact: test-results
          name: Kotest Tests
          path: "**/*.xml"
          reporter: java-junit
